
flags: {}
packages:
- .
extra-deps:
- dunai-0.4.0.0
- hspec-2.5.1
- hspec-core-2.5.1
- hspec-discover-2.5.1
- QuickCheck-2.11.3
- rhine-0.4.0.3
- rhine-gloss-0.4.0.0
- free-5.1
- time-1.8.0.4


resolver: lts-11.11
